{% set name = "termcolor" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/termcolor-{{ version }}.tar.gz
  sha256: 6a6dd7fbee581909eeec6a756cff1d7f7c376063b14e4a298dc4980309e55970

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatch-vcs
    - hatchling
  run:
    - python >={{ python_min }}

test:
  imports:
    - termcolor
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/termcolor/termcolor
  license: MIT
  license_file: COPYING.txt
  summary: ANSI color formatting for output in terminal

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - k-dominik
